base_url:
  marmay: "https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/africa/east/pentadal/chirps/seasaccum/marmay/anom/lta/downloads/pentadal/"
  octdec: "https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/fews/web/africa/east/pentadal/chirps/seasaccum/octdec/anom/lta/downloads/pentadal/"

exclude_year:

output:
  dataset: "east-africa-chirps-seasonal-rainfall-accumulation-anomaly-by-pentad"
  resource_desc:
    marmay: "March to May YYYY (Mar pentad 1 thru May Pentad 6) - Average(1981-2010)\nPentad: "
    octdec: "October to December YYYY (Oct pentad 1 thru Dec Pentad 6) - Average(1981-2010)\nPentad: "
  mapbox:
    ETH:
      marmay:
        name: "eth_chirps_marmay-0kiuw3"
        mapid: "humdata.adtgh6lr"
      octdec:
        name: "eth_chirps-octdec-582ypp"
        mapid: "humdata.9f35wnzq"
    KEN:
      marmay:
        name: "ken_chirps_marmay-588gpb"
        mapid: "humdata.bdidwt0g"
      octdec:
        name: "ken_chirps-octdec-8xn2th"
        mapid: "humdata.0zdu5z45"
    SOM:
      marmay:
        name: "som_chirps_marmay-02azfc"
        mapid: "humdata.7xxd10pv"
      octdec:
        name: "som_chirps-octdec-0uyngi"
        mapid: "humdata.1bl7k2zs"

boundaries:
  dataset: "unmap-international-boundaries-geojson"

legend:
  - range: [300, 100000]
    color: [37, 64, 97]
  - range: [200, 300]
    color: [30, 109, 235]
  - range: [100, 200]
    color: [58, 149, 245]
  - range: [50, 100]
    color: [120, 198, 250]
  - range: [25, 50]
    color: [181, 235, 250]
  - range: [10, 25]
    color: [119, 235, 115]
  - range: [-10, 10]
    color: [254, 254, 254]
  - range: [-25, -10]
    color: [240, 220, 185]
  - range: [-50, -25]
    color: [255, 233, 120]
  - range: [-100, -50]
    color: [255, 162, 0]
  - range: [-200, -100]
    color: [255, 51, 0]
  - range: [-300, -200]
    color: [163, 30, 30]
  - range: [-100000, -300]
    color: [105, 25, 26]
